[package]
name = "opengl-rs"
version = "0.1.0"
authors = ["Alexandre Chêne <kooparse@protonmail.com>"]

[dependencies]
gl = "0.6.0"
glutin = "0.14.0"
nalgebra = "0.14.0"
cgmath = "0.16.1"
image = "0.19.0"

[features]
wireframe = []
