[package]
name = "fuel"
version = "0.1.0"
authors = ["Alexandre Chêne <kooparse@protonmail.com>"]

[dependencies]
clippy = { git = "https://github.com/rust-lang-nursery/rust-clippy.git", branch = "master", optional = true }
gl = "0.6.0"
glutin = "0.14.0"
nalgebra = "0.14.0"
cgmath = "0.16.1"
image = "0.19.0"
